# Generated by Django 4.0.7 on 2022-11-22 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('info', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to='')),
                ('sponsorship_date', models.DateField(null=True)),
                ('sponsor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsors.sponsortype')),
            ],
        ),
    ]
