# Generated by Django 4.0.7 on 2022-11-23 16:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_date_end_homepage_date_start_and_more'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sponsors.sponsortype'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsorship_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HomePageSponsorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_sponsor_type', to='home.homepage')),
                ('sponsor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_type_home', to='sponsors.sponsortype')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_sponsor', to='home.homepage')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_home', to='sponsors.sponsor')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
