# Generated by Django 4.0.7 on 2022-12-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_logo_alter_sponsor_sponsor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
