# Generated by Django 4.0.7 on 2022-12-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_date_end_homepage_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
