# Generated by Django 4.0.7 on 2023-11-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_add_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='is_subcontent',
            field=models.BooleanField(default=False),
        ),
    ]
