# Generated by Django 4.0.7 on 2023-11-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pagecontent_is_subcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cfp_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsor_link',
            field=models.URLField(blank=True),
        ),
    ]
