# Generated by Django 4.0.7 on 2022-11-22 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, help_text='Short title to call the speaker, eg: CEO of X company', max_length=128)),
                ('display_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('abstract', models.TextField(blank=True)),
                ('presentation_type', models.CharField(choices=[('talk', 'Talk'), ('workshop', 'Workshop'), ('panel', 'Panel')], max_length=18)),
                ('presentation_date', models.DateField(null=True)),
                ('submitted_at', models.DateField(null=True)),
                ('is_accepted', models.BooleanField(null=True)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='presentations.speaker')),
            ],
        ),
    ]
